---
title: "Project proposal"
author: "omarxinyijohn"
output: github_document
---

```{r load-packages, message = FALSE}
library(tidyverse)
library(broom)
```

## 1. Introduction

The COVID-19 outbreak first reported in December, 2019 exploded into a global pandemic within weeks and still continues its spread with new waves of infections from new virus variants threatening regions across the globe even as authorities work to increase vaccination availability and roll out new mitigation measures. In the United States alone, more than 700,000 people have lost their lives due to COVID-19, but the vaccine has brought hope for a return to normal. 

The main research question that we will be exploring for this project is how cases and deaths have changed over time in the United States since the COVID-19 pandemic began. We are using two data files for this project, one of which includes cases and death data broken down by state and date, and the other which includes vaccination data broken down by state and date. Both data sources are publicly available on the CDC website. Links can be found in the data section of this proposal. A sampling of more specific questions include the following:

- Are there any seasonal changes in cases/deaths?
- How do changes differ across states?
- Which vaccines were more popular in certain states (J&J, Pfizer, Moderna)?
- Have vaccines reduced cases and/or deaths and if so, to what extent?

These are only some of our initial questions and we will likely try to ask and answer many more questions about these two datasets as we proceed through the project.



## 2. Data



## 3. Data analysis plan



