---
title: "Team contract"
author: "omarxinyijohn"
output: github_document
---

## Goals:

We want to improve our ability to analyze a given data set. In other words, we want to be able to ask questions about some data set and then answer those questions through some method of data analysis and visualization. For example, we might ask what is the relationship between variable x and variable y and then answer this by providing a plot that effectively demonstrates the relationship to whoever is viewing our document. Throughout this process we hope to refine our existing R skills as well as exploring new parts of the programming language that will enhance our analysis.

## Expectations:

- Everyone should be able to attend all team meetings on time.
- Everyone is expected to contribute to the work and respect the deadlines
- Make sure to communicate with the members of the group if you can’t meet a deadline or attend a meeting. 
- Please make sure to ask for help if needed


## Policies & Procedures:

- Show up to meetings we have planned together.
- Answer questions that we have for each other in a timely manner when communicating in person or digitally.
- Complete the assigned parts of the project in a timely manner

## Consequences:

We will do our best to communicate with each other and complete our assigned tasks. If any of us are not meeting the expectations outlined above, we will try to address it as a group either in class or digitally (over text, email, etc.). If issues are not resolved after addressing them to each other clearly and respectfully, then a group member may talk to Professor Baker about the issue. If a group member plans to go to Professor Baker about an issue, this should ideally be communicated with the group beforehand.

## Signatures

Omar Sarr John Mieszczanski Xinyi Zhang